apiVersion: apps/v1
kind: Deployment
metadata:
  name: apps-deployment
spec:
  selector:
    matchLabels:
      app: 2048app-k8s
  replicas: 1
  template:
    metadata:
      labels:
        app: 2048app-k8s
    spec:
      containers:
      - name: 2048app-k8s
        image: chathuracsddocker/2048gameapp
        ports:
        - containerPort: 80



---
apiVersion: v1
kind: Service
metadata:
  name: apps-service
spec:
  selector:
    app: 2048app-k8s
  ports:
  - protocol: "TCP"
    port: 80 # 
    targetPort: 80
    nodePort: 30001
  type: NodePort
